@startuml

entity USERS {
    * USERNAME : VARCHAR(30)
    P_HASH : CHAR(32)
}

entity RECIPES{
    * ID : INTEGER
    AUTHOR : VARCHAR(30) FK
    NAME : VARCHAR(30)
    DESCRIPTION : STRING
    BODY : STRING
}

entity RECIPE_INGREDIANTS{
 * RECIPE_ID : INTEGER FK
 * INGREDIANT_ID : INTERGER FK
}

entity INGREDIANTS{
    * INGREDIANT_ID : INTEGER
    NAME : STRING
}

USERS ||--|{ RECIPES
RECIPES }|--|{ INGREDIANTS
RECIPES ||--|{ RECIPE_INGREDIANTS
INGREDIANTS ||--|{ RECIPE_INGREDIANTS

@enduml